/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: aab7fbbc8ef6dee96d8a657473adbd09)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/site-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
